# Haproxy Config
haproxy_config_file: dev/redis_test/haproxy.cfg
# Redis Config
data_dir: "/data/redis-data"
config_dir: "/data/redis-config"
# Fixed version for Ubuntu 22 for an example.
redis_version: "6:6.2.14-1rl1~jammy1"
# Sentinel config
failover_timeout: 30000
down_after_milliseconds: 5000
# Others
cluster: "kienlt-test-redis-cluster"